# Auto-generated onboarding configuration

config = {
    "agent_name": "Alex",
    "agent_description": "Handles customer inquiries, provides assistance, and ensures excellent customer service.",
    "model": "gpt-5",
    "enable_guardrail": True,
    "company_name": "Agencii AI",
    "company_overview": "Agencii AI is a platform for building reliable AI agents on top of the OpenAI API. Users can create valuable solutions for their own or their clients' businesses.",
    "output_format": "Provide clear, well-structured responses. Use the selected response structure and style. Include relevant examples when helpful.",
    "support_contact": None,
    "additional_context": None,
    "knowledge_files": [],
    "openapi_schema": "\n        {\n  \"openapi\": \"3.1.0\",\n  \"info\": {\n    \"title\": \"Send Project Info\",\n    \"description\": \"Send customer support request.\",\n    \"version\": \"v1.0.0\"\n  },\n  \"servers\": [\n    {\n      \"url\": \"https://us-central1-openai-widget.cloudfunctions.net/httpCreateContact\"\n    }\n  ],\n  \"paths\": {\n    \"/\": {\n      \"post\": {\n        \"description\": \"Use this function to send a new support ticket or feedback from the customer. Make sure to ask the customer for all the information required before using this tool.\",\n        \"operationId\": \"sendSupportRequest\",\n        \"parameters\": [],\n        \"requestBody\": {\n          \"content\": {\n            \"application/json\": {\n              \"schema\": {\n                \"$ref\": \"#/components/schemas/SendProjectInfo\"\n              }\n            }\n          },\n          \"required\": true\n        },\n        \"deprecated\": false,\n        \"security\": [\n          {\n            \"apiKey\": []\n          }\n        ]\n      }\n    }\n  },\n  \"components\": {\n    \"schemas\": {\n      \"SendProjectInfo\": {\n        \"properties\": {\n          \"firstName\": {\n            \"description\": \"First name of the customer.\",\n            \"title\": \"Firstname\",\n            \"type\": \"string\"\n          },\n          \"lastName\": {\n            \"anyOf\": [\n              {\n                \"type\": \"string\"\n              },\n              {\n                \"type\": \"null\"\n              }\n            ],\n            \"description\": \"Last name of the customer.\",\n            \"title\": \"Lastname\"\n          },\n          \"email\": {\n            \"description\": \"Email address of the customer.\",\n            \"title\": \"Email\",\n            \"type\": \"string\"\n          },\n          \"inquiryType\": {\n            \"description\": \"Type of the inquiry.\",\n            \"enum\": [\n              \"technicalSupport\",\n              \"salesInquiry\",\n              \"generalQuestion\",\n              \"feedback\"\n            ],\n            \"title\": \"Inquirytype\",\n            \"type\": \"string\"\n          },\n          \"message\": {\n            \"description\": \"Message with information about their request.\",\n            \"title\": \"Message\",\n            \"type\": \"string\"\n          }\n        },\n        \"required\": [\n          \"email\",\n          \"firstName\",\n          \"inquiryType\",\n          \"lastName\",\n          \"message\"\n        ],\n        \"type\": \"object\"\n      }\n    },\n    \"securitySchemes\": {\n      \"apiKey\": {\n        \"type\": \"apiKey\"\n      }\n    }\n  }\n}"
}
